### ISSUE TITLE
Come gestire i servizi

### ISSUE THREAD

**Issue by Giulia2Gargano** [Giulia2Gargano/KeZapp-ill#2]
Dal lato server ci troviamo in difficoltà nella gestione dei servizi. 
Potrebbe spiegarci brevemente come gestirli, basandoci su ciò che c'è scritto nello schema da lei fornitoci? 
Dovremmo usare una soluzione simile a quelle già viste negli esercizi precedenti (es.rubrica ->
` public List<Contatto> rubricaAgg(Contatto c) {
        contattoRepository.save(c);
        return ritornaLista();
}`
)o adottare una strategia diversa?

**Comment by luca-lezzerini** [comment]
La domanda non mi è molto chiara, ma credo si possa affermare che l'approccio è quello proposto nell'ultimo paragrafo, ossia di aggiornare il DB e subito dopo chiamare il servizio che ritorna tutte le entità su DB (i.e. la tabella)
