### ISSUE TITLE
I servizi dal gruppo individuati sono corretti?

### ISSUE THREAD

**Issue by Giulia2Gargano** [Giulia2Gargano/KeZapp-ill#3]
![image](https://user-images.githubusercontent.com/78588316/109523561-c8b36e80-7aaf-11eb-965c-ca01bff48e57.png)
Questi sono i servizi che abbiamo individuato, potrebbe dirci se sono giusti e/o eventualmente ce ne occorrono degli altri?

**Comment by luca-lezzerini** [comment]
Sì, sono corretti

**Comment by Giulia2Gargano** [comment]
Perfetto, grazie!
