### ISSUE TITLE
Problema Classe KeZappServiceImpl "-/deleted"

### ISSUE THREAD

**Issue by MatteoPalombo99** [Giulia2Gargano/KeZapp-ill#4]
![image](https://user-images.githubusercontent.com/78491909/109691385-adb42d80-7b87-11eb-8ad0-5ec7e2837600.png)
Nonostante io elimini sia la classe che il package ServiceImpl, il nome della classe rimane sbiadito e contrassegnata con "-/deleted"

**Comment by luca-lezzerini** [comment]
Provi a committare e fare push, dovrebbe scomparire
