### ISSUE TITLE
Problemi di scambio dati tra client e server

### ISSUE THREAD

**Issue by Giulia2Gargano** [Giulia2Gargano/KeZapp-ill#5]
siamo riusciti ad associare l'id alla sessione e a sarvarlo sul db, ma quando facciamo la query sul db non ci torna alcun nickname

**Comment by luca-lezzerini** [comment]
Magari se mi mettete un copia e incolla del codice evito di andare dall'astrologa ...

**Comment by Giulia2Gargano** [comment]
`public RegistrazioneDto registrazione(RichiediRegistrazioneDto reqregDto) {
        Chat ch = new Chat(reqregDto.getNickname());
        keZappRepositoryChat.save(ch);
        ch.setSessione(Long.toString(ch.getId()));
        keZappRepositoryChat.save(ch);
        return new RegistrazioneDto();
        //creare nuovA CHat con i dati ri`
lato server
`registrazione() {

    let req = new RichiediRegistrazioneDto();
    req.nickname = this.contatto.nickname;
    let oss = this.http.post<RegistrazioneDto>("http://localhost:8080/registrazione", req);
    oss.subscribe(r => {
      this.contatti = r.contatti;
      this.sessione = r.sessione;
    });
    this.contatto = new Chat();

  }`

**Comment by luca-lezzerini** [comment]
Console?
Controller?
Log lato server?
