### ISSUE TITLE
Problema con Xampp. Dice che la porta 80 è occupata.

### ISSUE THREAD

**Issue by Giulia2Gargano** [Giulia2Gargano/KeZapp-ill#6]
Xampp dice che la porta 80 è occupata ed io non so come gestire la cosa, ho cercato di aprire i service ma non ho trovato nulla. 
Ho chiuso e riaperto Xampp svariate volte e addirittura ravviato il computer ma non cambia nulla. E' già la seconda volta che lo elimino e ri-installo, c'è un altro modo per risolvere la questione?
![image](https://user-images.githubusercontent.com/78588316/109882896-dc5f0080-7c7a-11eb-83fb-4a521c4c9663.png)
Addirittura ora che ho riaperto Xampp per farle lo screen non menziona più la porta 80.
Io a causa di questo problema non ho potuto scrivere codice, poichè non potevo in alcun modo testarlo, quindi ho dovuto limitarmi a seguire il collega.

**Comment by luca-lezzerini** [comment]
La porta 80 è quella del web server Apache che non le serve per far girare il programma. Le serve solo per far girare phpmyadmin che è l'equivalente di mysql workbench. Dovrebbe essere sufficiente il solo mysql che gira sulla  porta 3306

**Comment by Giulia2Gargano** [comment]
Non avendo ancora risolto, che faccio? Chiudo il ticket o lo lascio aperto?
